// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/archetypes/raw_bytes_query.fbs".

#pragma once

#include "../../blueprint/components/chunk_size.hpp"
#include "../../blueprint/components/filter_by_range.hpp"
#include "../../blueprint/components/numeric_base.hpp"
#include "../../collection.hpp"
#include "../../component_batch.hpp"
#include "../../component_column.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::blueprint::archetypes {
    /// **Archetype**: A query of a single binary piece of data, for use with `archetypes::RawBytes`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct RawBytesQuery {
        /// Numeric base to display bytes in
        std::optional<ComponentBatch> base;

        /// How many columns to display per row
        std::optional<ComponentBatch> width;

        /// Range to filter the bytes from
        std::optional<ComponentBatch> range;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.blueprint.archetypes.RawBytesQuery";

        /// `ComponentDescriptor` for the `base` field.
        static constexpr auto Descriptor_base = ComponentDescriptor(
            ArchetypeName, "RawBytesQuery:base",
            Loggable<rerun::blueprint::components::NumericBase>::ComponentType
        );
        /// `ComponentDescriptor` for the `width` field.
        static constexpr auto Descriptor_width = ComponentDescriptor(
            ArchetypeName, "RawBytesQuery:width",
            Loggable<rerun::blueprint::components::ChunkSize>::ComponentType
        );
        /// `ComponentDescriptor` for the `range` field.
        static constexpr auto Descriptor_range = ComponentDescriptor(
            ArchetypeName, "RawBytesQuery:range",
            Loggable<rerun::blueprint::components::FilterByRange>::ComponentType
        );

      public:
        RawBytesQuery() = default;
        RawBytesQuery(RawBytesQuery&& other) = default;
        RawBytesQuery(const RawBytesQuery& other) = default;
        RawBytesQuery& operator=(const RawBytesQuery& other) = default;
        RawBytesQuery& operator=(RawBytesQuery&& other) = default;

        explicit RawBytesQuery(
            rerun::blueprint::components::NumericBase _base,
            rerun::blueprint::components::ChunkSize _width,
            rerun::blueprint::components::FilterByRange _range
        )
            : base(ComponentBatch::from_loggable(std::move(_base), Descriptor_base).value_or_throw()
              ),
              width(ComponentBatch::from_loggable(std::move(_width), Descriptor_width)
                        .value_or_throw()),
              range(ComponentBatch::from_loggable(std::move(_range), Descriptor_range)
                        .value_or_throw()) {}

        /// Update only some specific fields of a `RawBytesQuery`.
        static RawBytesQuery update_fields() {
            return RawBytesQuery();
        }

        /// Clear all the fields of a `RawBytesQuery`.
        static RawBytesQuery clear_fields();

        /// Numeric base to display bytes in
        RawBytesQuery with_base(const rerun::blueprint::components::NumericBase& _base) && {
            base = ComponentBatch::from_loggable(_base, Descriptor_base).value_or_throw();
            return std::move(*this);
        }

        /// How many columns to display per row
        RawBytesQuery with_width(const rerun::blueprint::components::ChunkSize& _width) && {
            width = ComponentBatch::from_loggable(_width, Descriptor_width).value_or_throw();
            return std::move(*this);
        }

        /// Range to filter the bytes from
        RawBytesQuery with_range(const rerun::blueprint::components::FilterByRange& _range) && {
            range = ComponentBatch::from_loggable(_range, Descriptor_range).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::blueprint::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<blueprint::archetypes::RawBytesQuery> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const blueprint::archetypes::RawBytesQuery& archetype
        );
    };
} // namespace rerun
