// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/archetypes/raw_bytes_query.fbs".

#include "raw_bytes_query.hpp"

#include "../../collection_adapter_builtins.hpp"

namespace rerun::blueprint::archetypes {
    RawBytesQuery RawBytesQuery::clear_fields() {
        auto archetype = RawBytesQuery();
        archetype.base =
            ComponentBatch::empty<rerun::blueprint::components::NumericBase>(Descriptor_base)
                .value_or_throw();
        archetype.width =
            ComponentBatch::empty<rerun::blueprint::components::ChunkSize>(Descriptor_width)
                .value_or_throw();
        archetype.range =
            ComponentBatch::empty<rerun::blueprint::components::FilterByRange>(Descriptor_range)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> RawBytesQuery::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(3);
        if (base.has_value()) {
            columns.push_back(base.value().partitioned(lengths_).value_or_throw());
        }
        if (width.has_value()) {
            columns.push_back(width.value().partitioned(lengths_).value_or_throw());
        }
        if (range.has_value()) {
            columns.push_back(range.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> RawBytesQuery::columns() {
        if (base.has_value()) {
            return columns(std::vector<uint32_t>(base.value().length(), 1));
        }
        if (width.has_value()) {
            return columns(std::vector<uint32_t>(width.value().length(), 1));
        }
        if (range.has_value()) {
            return columns(std::vector<uint32_t>(range.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::blueprint::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>>
        AsComponents<blueprint::archetypes::RawBytesQuery>::as_batches(
            const blueprint::archetypes::RawBytesQuery& archetype
        ) {
        using namespace blueprint::archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(3);

        if (archetype.base.has_value()) {
            cells.push_back(archetype.base.value());
        }
        if (archetype.width.has_value()) {
            cells.push_back(archetype.width.value());
        }
        if (archetype.range.has_value()) {
            cells.push_back(archetype.range.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
