// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/components/numeric_base.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Common bases a number can be represented in
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, Default, strum::EnumIter)]
#[repr(u8)]
pub enum NumericBase {
    /// Binary (base-2)
    Binary = 2,

    /// Octal (base-8)
    Octal = 8,

    /// Decimal (base-10)
    Decimal = 10,

    /// Hexadecimal (base-16)
    #[default]
    Hex = 16,
}

impl ::re_types_core::Component for NumericBase {
    #[inline]
    fn name() -> ComponentType {
        "rerun.blueprint.components.NumericBase".into()
    }
}

::re_types_core::macros::impl_into_cow!(NumericBase);

impl ::re_types_core::Loggable for NumericBase {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt8
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u8);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt8Type>::new(
                ScalarBuffer::from(
                    data0
                        .into_iter()
                        .map(|v| v.unwrap_or_default())
                        .collect::<Vec<_>>(),
                ),
                data0_validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .as_any()
            .downcast_ref::<UInt8Array>()
            .ok_or_else(|| {
                let expected = Self::arrow_datatype();
                let actual = arrow_data.data_type().clone();
                DeserializationError::datatype_mismatch(expected, actual)
            })
            .with_context("rerun.blueprint.components.NumericBase#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(val) => <Self as ::re_types_core::reflection::Enum>::try_from_integer(val)
                    .map(Some)
                    .ok_or_else(|| {
                        DeserializationError::missing_union_arm(
                            Self::arrow_datatype(),
                            "<invalid>",
                            val as _,
                        )
                    }),
                None => Ok(None),
            })
            .collect::<DeserializationResult<Vec<Option<_>>>>()
            .with_context("rerun.blueprint.components.NumericBase")?)
    }
}

impl std::fmt::Display for NumericBase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Binary => write!(f, "Binary"),
            Self::Octal => write!(f, "Octal"),
            Self::Decimal => write!(f, "Decimal"),
            Self::Hex => write!(f, "Hex"),
        }
    }
}

impl ::re_types_core::reflection::Enum for NumericBase {
    type Repr = u8;

    #[inline]
    fn variants() -> &'static [Self] {
        &[Self::Binary, Self::Octal, Self::Decimal, Self::Hex]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::Binary => "Binary (base-2)",
            Self::Octal => "Octal (base-8)",
            Self::Decimal => "Decimal (base-10)",
            Self::Hex => "Hexadecimal (base-16)",
        }
    }

    #[inline]
    fn try_from_integer(value: u8) -> Option<Self> {
        match value {
            2 => Some(Self::Binary),
            8 => Some(Self::Octal),
            10 => Some(Self::Decimal),
            16 => Some(Self::Hex),
            _ => None,
        }
    }
}

impl ::re_byte_size::SizeBytes for NumericBase {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        0
    }

    #[inline]
    fn is_pod() -> bool {
        true
    }
}
