// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/archetypes/raw_bytes_query.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A query of a single binary piece of data, for use with [`archetypes::RawBytes`][crate::archetypes::RawBytes].
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
#[derive(Clone, Debug, Default)]
pub struct RawBytesQuery {
    /// Numeric base to display bytes in
    pub base: Option<SerializedComponentBatch>,

    /// How many columns to display per row
    pub width: Option<SerializedComponentBatch>,

    /// Range to filter the bytes from
    pub range: Option<SerializedComponentBatch>,
}

impl RawBytesQuery {
    /// Returns the [`ComponentDescriptor`] for [`Self::base`].
    ///
    /// The corresponding component is [`crate::blueprint::components::NumericBase`].
    #[inline]
    pub fn descriptor_base() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.RawBytesQuery".into()),
            component: "RawBytesQuery:base".into(),
            component_type: Some("rerun.blueprint.components.NumericBase".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::width`].
    ///
    /// The corresponding component is [`crate::blueprint::components::ChunkSize`].
    #[inline]
    pub fn descriptor_width() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.RawBytesQuery".into()),
            component: "RawBytesQuery:width".into(),
            component_type: Some("rerun.blueprint.components.ChunkSize".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::range`].
    ///
    /// The corresponding component is [`crate::blueprint::components::FilterByRange`].
    #[inline]
    pub fn descriptor_range() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.blueprint.archetypes.RawBytesQuery".into()),
            component: "RawBytesQuery:range".into(),
            component_type: Some("rerun.blueprint.components.FilterByRange".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            RawBytesQuery::descriptor_base(),
            RawBytesQuery::descriptor_width(),
            RawBytesQuery::descriptor_range(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 3usize]> =
    std::sync::LazyLock::new(|| {
        [
            RawBytesQuery::descriptor_base(),
            RawBytesQuery::descriptor_width(),
            RawBytesQuery::descriptor_range(),
        ]
    });

impl RawBytesQuery {
    /// The total number of components in the archetype: 3 required, 0 recommended, 0 optional
    pub const NUM_COMPONENTS: usize = 3usize;
}

impl ::re_types_core::Archetype for RawBytesQuery {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.blueprint.archetypes.RawBytesQuery".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Raw bytes query"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let base = arrays_by_descr
            .get(&Self::descriptor_base())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_base()));
        let width = arrays_by_descr
            .get(&Self::descriptor_width())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_width()));
        let range = arrays_by_descr
            .get(&Self::descriptor_range())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_range()));
        Ok(Self { base, width, range })
    }
}

impl ::re_types_core::AsComponents for RawBytesQuery {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.base.clone(), self.width.clone(), self.range.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for RawBytesQuery {}

impl RawBytesQuery {
    /// Create a new `RawBytesQuery`.
    #[inline]
    pub fn new(
        base: impl Into<crate::blueprint::components::NumericBase>,
        width: impl Into<crate::blueprint::components::ChunkSize>,
        range: impl Into<crate::blueprint::components::FilterByRange>,
    ) -> Self {
        Self {
            base: try_serialize_field(Self::descriptor_base(), [base]),
            width: try_serialize_field(Self::descriptor_width(), [width]),
            range: try_serialize_field(Self::descriptor_range(), [range]),
        }
    }

    /// Update only some specific fields of a `RawBytesQuery`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `RawBytesQuery`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            base: Some(SerializedComponentBatch::new(
                crate::blueprint::components::NumericBase::arrow_empty(),
                Self::descriptor_base(),
            )),
            width: Some(SerializedComponentBatch::new(
                crate::blueprint::components::ChunkSize::arrow_empty(),
                Self::descriptor_width(),
            )),
            range: Some(SerializedComponentBatch::new(
                crate::blueprint::components::FilterByRange::arrow_empty(),
                Self::descriptor_range(),
            )),
        }
    }

    /// Numeric base to display bytes in
    #[inline]
    pub fn with_base(mut self, base: impl Into<crate::blueprint::components::NumericBase>) -> Self {
        self.base = try_serialize_field(Self::descriptor_base(), [base]);
        self
    }

    /// How many columns to display per row
    #[inline]
    pub fn with_width(mut self, width: impl Into<crate::blueprint::components::ChunkSize>) -> Self {
        self.width = try_serialize_field(Self::descriptor_width(), [width]);
        self
    }

    /// Range to filter the bytes from
    #[inline]
    pub fn with_range(
        mut self,
        range: impl Into<crate::blueprint::components::FilterByRange>,
    ) -> Self {
        self.range = try_serialize_field(Self::descriptor_range(), [range]);
        self
    }
}

impl ::re_byte_size::SizeBytes for RawBytesQuery {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.base.heap_size_bytes() + self.width.heap_size_bytes() + self.range.heap_size_bytes()
    }
}
