# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/archetypes/raw_bytes_query.fbs".

# You can extend this class by creating a "RawBytesQueryExt" class in "raw_bytes_query_ext.py".

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar

from attrs import define, field

from ..._baseclasses import (
    Archetype,
    ComponentDescriptor,
)
from ...blueprint import components as blueprint_components, datatypes as blueprint_datatypes
from ...error_utils import catch_and_log_exceptions

if TYPE_CHECKING:
    from ... import datatypes

__all__ = ["RawBytesQuery"]


@define(str=False, repr=False, init=False)
class RawBytesQuery(Archetype):
    """
    **Archetype**: A query of a single binary piece of data, for use with [`archetypes.RawBytes`][rerun.archetypes.RawBytes].

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    NAME: ClassVar[str] = "rerun.blueprint.archetypes.RawBytesQuery"

    def __init__(
        self: Any,
        *,
        base: blueprint_components.NumericBaseLike,
        width: datatypes.TimeIntLike,
        range: blueprint_datatypes.FilterByRangeLike,
    ) -> None:
        """
        Create a new instance of the RawBytesQuery archetype.

        Parameters
        ----------
        base:
            Numeric base to display bytes in
        width:
            How many columns to display per row
        range:
            Range to filter the bytes from

        """

        # You can define your own __init__ function as a member of RawBytesQueryExt in raw_bytes_query_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(base=base, width=width, range=range)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            base=None,
            width=None,
            range=None,
        )

    @classmethod
    def _clear(cls) -> RawBytesQuery:
        """Produce an empty RawBytesQuery, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        base: blueprint_components.NumericBaseLike | None = None,
        width: datatypes.TimeIntLike | None = None,
        range: blueprint_datatypes.FilterByRangeLike | None = None,
    ) -> RawBytesQuery:
        """
        Update only some specific fields of a `RawBytesQuery`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        base:
            Numeric base to display bytes in
        width:
            How many columns to display per row
        range:
            Range to filter the bytes from

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "base": base,
                "width": width,
                "range": range,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> RawBytesQuery:
        """Clear all the fields of a `RawBytesQuery`."""
        return cls.from_fields(clear_unset=True)

    @staticmethod
    def descriptor_base() -> ComponentDescriptor:
        return ComponentDescriptor(
            "RawBytesQuery:base",
            archetype=RawBytesQuery.NAME,
            component_type=blueprint_components.NumericBaseBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_width() -> ComponentDescriptor:
        return ComponentDescriptor(
            "RawBytesQuery:width",
            archetype=RawBytesQuery.NAME,
            component_type=blueprint_components.ChunkSizeBatch._COMPONENT_TYPE,
        )

    @staticmethod
    def descriptor_range() -> ComponentDescriptor:
        return ComponentDescriptor(
            "RawBytesQuery:range",
            archetype=RawBytesQuery.NAME,
            component_type=blueprint_components.FilterByRangeBatch._COMPONENT_TYPE,
        )

    base: blueprint_components.NumericBaseBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.NumericBaseBatch._converter,  # type: ignore[misc]
    )
    # Numeric base to display bytes in
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    width: blueprint_components.ChunkSizeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.ChunkSizeBatch._converter,  # type: ignore[misc]
    )
    # How many columns to display per row
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    range: blueprint_components.FilterByRangeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.FilterByRangeBatch._converter,  # type: ignore[misc]
    )
    # Range to filter the bytes from
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
