// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/raw_bytes.fbs".

#include "raw_bytes.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    RawBytes RawBytes::clear_fields() {
        auto archetype = RawBytes();
        archetype.blob =
            ComponentBatch::empty<rerun::components::Blob>(Descriptor_blob).value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> RawBytes::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(1);
        if (blob.has_value()) {
            columns.push_back(blob.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> RawBytes::columns() {
        if (blob.has_value()) {
            return columns(std::vector<uint32_t>(blob.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::RawBytes>::as_batches(
        const archetypes::RawBytes& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(1);

        if (archetype.blob.has_value()) {
            cells.push_back(archetype.blob.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
