# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/components/chunk_size.fbs".

# You can extend this class by creating a "ChunkSizeExt" class in "chunk_size_ext.py".

from __future__ import annotations

from ... import datatypes
from ..._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChunkSize", "ChunkSizeBatch"]


class ChunkSize(datatypes.TimeInt, ComponentMixin):
    """
    **Component**: Describes the width of a byte chunk.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChunkSizeExt in chunk_size_ext.py

    # Note: there are no fields here because ChunkSize delegates to datatypes.TimeInt


class ChunkSizeBatch(datatypes.TimeIntBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.blueprint.components.ChunkSize"


# This is patched in late to avoid circular dependencies.
ChunkSize._BATCH_TYPE = ChunkSizeBatch  # type: ignore[assignment]
