# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/components/numeric_base.fbs".

# You can extend this class by creating a "NumericBaseExt" class in "numeric_base_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from ..._baseclasses import (
    BaseBatch,
    ComponentBatchMixin,
)

__all__ = ["NumericBase", "NumericBaseArrayLike", "NumericBaseBatch", "NumericBaseLike"]


from enum import Enum


class NumericBase(Enum):
    """**Component**: Common bases a number can be represented in."""

    Binary = 2
    """Binary (base-2)"""

    Octal = 8
    """Octal (base-8)"""

    Decimal = 10
    """Decimal (base-10)"""

    Hex = 16
    """Hexadecimal (base-16)"""

    @classmethod
    def auto(cls, val: str | int | NumericBase) -> NumericBase:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, NumericBase):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


NumericBaseLike = NumericBase | Literal["Binary", "Decimal", "Hex", "Octal", "binary", "decimal", "hex", "octal"] | int
"""A type alias for any NumericBase-like object."""

NumericBaseArrayLike = (
    NumericBase
    | Literal["Binary", "Decimal", "Hex", "Octal", "binary", "decimal", "hex", "octal"]
    | int
    | Sequence[NumericBaseLike]
)
"""A type alias for any NumericBase-like array object."""


class NumericBaseBatch(BaseBatch[NumericBaseArrayLike], ComponentBatchMixin):
    _ARROW_DATATYPE = pa.uint8()
    _COMPONENT_TYPE: str = "rerun.blueprint.components.NumericBase"

    @staticmethod
    def _native_to_pa_array(data: NumericBaseArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (NumericBase, int, str)):
            data = [data]

        pa_data = [NumericBase.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]  # ty: ignore[not-iterable]

        return pa.array(pa_data, type=data_type)
